# The load balancer uses MetalLb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: loadbalancer
spec:
  interval: 15m
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: loadbalancer
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 5m
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadbalancer
  labels:
    name: loadbalancer
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: loadbalancer
spec:
  addresses:
    - 192.168.2.100
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv
  namespace: loadbalancer
spec:
  ipAddressPools:
    - main-pool
