# The load balancer uses MetalLb
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: loadbalancer
spec:
  interval: 15m
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: loadbalancer
spec:
  interval: 15m
  timeout: 5m
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 5m
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadbalancer
  labels:
    name: loadbalancer
