apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: collector
  namespace: open-telemetry
spec:
  serviceAccount: otelcollector
  volumes:
    - name: hostfs
      hostPath:
        path: /
  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
      readOnly: true
      mountPropagation: HostToContainer
  mode: daemonset
  config:
    receivers:
      hostmetrics:
        root_path: /hostfs
        scrapers:
          cpu:
          filesystem:
          memory:
      k8s_cluster:
        allocatable_types_to_report:
          - cpu
          - memory
          - pods
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      k8s_attributes:
      resourcedetection:
        detectors: [system, k8snode]
        override: false

    exporters:
      otlp_grpc:
        endpoint: 192.168.2.10:4317
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: "debug"
      pipelines:
        metrics:
          receivers: [hostmetrics,otlp,k8s_cluster]
          processors: [k8s_attributes, resourcedetection]
          exporters: [otlp_grpc]
