---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cert-manager-repository
  namespace: helm
spec:
  interval: 15m
  url: oci://quay.io/jetstack/charts/cert-manager
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: helm
spec:
  interval: 15m
  timeout: 5m
  targetNamespace: cert-manager
  chartRef:
    kind: OCIRepository
    name: cert-manager-repository
  chart:
    spec:
      chart: external-secrets
      interval: 5m
