---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-repository
  namespace: helm
spec:
  interval: 15m
  url: oci://quay.io/jetstack/charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: helm
spec:
  interval: 15m
  timeout: 10m
  targetNamespace: cert-manager
  chart:
    spec:
      reconcileStrategy: ChartVersion
      chart: cert-manager
      version: 1.12.x
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repository
      interval: 5m
  values:
    crds:
      enabled: true
